POST https://node-do-zero-3l5z.onrender.com/videos
Content-Type: application/json

{
  "title": "video 01",
  "description": "Esse é o primeiro video do banco.",
  "duration": "180"
}

###
GET https://node-do-zero-3l5z.onrender.com/videos

###
PUT https://node-do-zero-3l5z.onrender.com/videos/c3329b5b-8e47-4def-bc07-a3ed80d21d26
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o primeiro video do banco.",
  "duration": "180"
}

###
DELETE https://node-do-zero-3l5z.onrender.com/videos/c3329b5b-8e47-4def-bc07-a3ed80d21d26
